# COLUMNS:
#   fixed acidity: float64
#   volatile acidity: float64
#   citric acid: float64
#   residual sugar: float64
#   chlorides: float64
#   free sulfur dioxide: float64
#   total sulfur dioxide: float64
#   density: float64
#   pH: float64
#   sulphates: float64
#   alcohol: float64
#   quality: int64


# TARGET_COLUMN:
#   name: quality
COLUMNS:
  person_age: float64
  person_income: float64
  loan_amnt: float64
  loan_int_rate: float64
  cb_person_cred_hist_length: float64
  loan_status: int64

TARGET_COLUMN:
  name: loan_status  