import os
import joblib
import pandas as pd
import numpy as np
from mlProject import logger
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from mlProject.entity.config_entity import DataTransformationConfig

class DataTransformation:
    def __init__(self, config: DataTransformationConfig):
        self.config = config

    def get_transformer_object(self) -> ColumnTransformer:
        """
        Dynamically generates an institutional processing pipeline 
        by inspecting data types listed in schema.yaml. Zero hardcoding.
        """
        try:
            numerical_cols = []
            categorical_cols = []

            # Segregate columns dynamically based on schema types
            for col_name, col_type in self.config.schema_columns.items():
                if col_name == self.config.target_column:
                    continue  # Protect the target feature

                if col_type in ['float64', 'int64', 'float', 'int']:
                    numerical_cols.append(col_name)
                else:
                    categorical_cols.append(col_name)

            logger.info(f"Dynamic Numeric Pipeline Scope: {numerical_cols}")
            logger.info(f"Dynamic Categorical Pipeline Scope: {categorical_cols}")

            # Define localized processing pipelines
            num_pipeline = Pipeline(steps=[
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler())
            ])

            cat_pipeline = Pipeline(steps=[
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("one_hot", OneHotEncoder(drop="first", handle_unknown="ignore", sparse_output=False))
            ])

            # Bundle configurations dynamically
            preprocessor = ColumnTransformer(transformers=[
                ("num_pipeline", num_pipeline, numerical_cols),
                ("cat_pipeline", cat_pipeline, categorical_cols)
            ])

            return preprocessor

        except Exception as e:
            raise e

    def train_test_splitting(self):
        try:
            data = pd.read_csv(self.config.data_path)

            # Defensive Data Cleaning: Filter out biological/operational anomalies if present
            if 'person_age' in data.columns:
                data = data[data['person_age'] <= 100].copy()
            if 'person_emp_length' in data.columns:
                data = data[data['person_emp_length'] <= 60].copy()

            # Separate feature matrix and targets dynamically
            X = data.drop([self.config.target_column], axis=1)
            y = data[self.config.target_column]

            # Execute stratified train-test splitting
            X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

            # Fetch the dynamic transformer object
            preprocessing_obj = self.get_transformer_object()

            logger.info("Transforming datasets through structural processing matrix...")
            X_train_arr = preprocessing_obj.fit_transform(X_train)
            X_test_arr = preprocessing_obj.transform(X_test)

            # --- EXTRACT FEATURE NAMES ---
            # Retrieve the exact column names generated by the transformer
            feature_names = preprocessing_obj.get_feature_names_out()

            # --- NEW EXPLICIT NAMING LOGIC ---
            # Convert transformed arrays back to DataFrames AND apply the feature names
            train_df = pd.DataFrame(X_train_arr, columns=feature_names)
            test_df = pd.DataFrame(X_test_arr, columns=feature_names)

            # Explicitly append the target column using the name from schema.yaml
            train_df[self.config.target_column] = y_train.values
            test_df[self.config.target_column] = y_test.values

            # Save clean processing arrays as standard CSV records with headers!
            train_df.to_csv(os.path.join(self.config.root_dir, "train.csv"), index=False)
            test_df.to_csv(os.path.join(self.config.root_dir, "test.csv"), index=False)

            # Save the preprocessor binary for use by the inference loop
            preprocessor_path = os.path.join(self.config.root_dir, "preprocessor.pkl")
            joblib.dump(preprocessing_obj, preprocessor_path)

            logger.info("Successfully completed data transformations.")
            logger.info(f"Training Matrix Dimensions: {train_df.shape}")
            logger.info(f"Testing Matrix Dimensions: {test_df.shape}")
            logger.info(f"Preprocessor serialized at: {preprocessor_path}")

        except Exception as e:
            raise e